spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/yunyun?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
      username: yunyun
      password: 你的数据库密码
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 50

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: false

music:
  storage-path: /www/wwwroot/yunyun/music-player
